#!/usr/bin/env ruby

# Configures the git author to a list of developers when pair programming
#
# Usage: pair lm bh (Sets the author to 'Luke Melia and Bryan Helmkamp')
#        pair       (Unsets the author so the git global config takes effect)
#
# Author: Bryan Helmkamp (http://brynary.com)
# http://www.brynary.com/2008/9/1/setting-the-git-commit-author-to-pair-programmers-names

#######################################################################
## Configuration

PAIR_EMAIL = "pair@thinkrelevance.com"

AUTHORS = {
  "ab" => "Aaron Bedra",
  "ad" => "Alan Dipert",
  "ar" => "Alex Redington",
  "aw" => "Alex Warr",
  "ba" => "Brenton Ashworth",
  "bc" => "Bobby Calderwood",
  "bg" => "Bradley Grzesiak",
  "bv" => "Ben Vandgrift",
  "ca" => "Craig Andera",
  "cd" => "Craig Demyanovich",
  "ch" => "Chad Humphries",
  "cn" => "Clinton Nixon",
  "cr" => "Chris Redinger",
  "dl" => "David Liebke",
  "dm" => "Don Mullen",
  "do" => "Duff OMelia",
  "dw" => "Devin Walters",
  "em" => "Eric Meyer",
  "gp" => "Geoff Parsons",
  "hg" => "Heow Goodman",
  "jb" => "Justin Blake",
  "jd" => "Jon Distad",
  "jf" => "Jeff Felchner",
  "jg" => "Justin Gehtland",
  "jk" => "Jamie Kite",
  "jm" => "Jess Martin",
  "jam"  => "Jen Myers",
  "jp" => "Jared Pace",
  "jr" => "Jason Rudolph",
  "jsg" => "Jonathan Greenberg",
  "jy" => "Jack Dempsey",
  "ka" => "Kevin Altman",
  "ld" => "Lake Denman",
  "lk" => "Larry Karnowski",
  "lv" => "Luke VanderHart",
  "ma" => "Muness Alrubaie",
  "mf" => "Michael Fogus",
  "mh" => "Michael Harrison",
  "mn" => "Michael Nygard",
  "mp" => "Michael Parenteau",
  "np" => "Nick Plante",
  "pp" => "Paul Pagel",
  "ro" => "Russ Olsen",
  "rs" => "Rob Sanheim",
  "es" => "Ezra Spier",
  "sa" => "Stephen Anderson",
  "sb" => "Sam Beam",
  "sf" => "Shay Frendt",
  "sh" => "Stuart Halloway",
  "sk" => "Steve Kim",
  "ss" => "Stuart Sierra",
  "su" => "Sam Umbach",
  "te" => "Tim Ewald",
  "vr" => "Vojto Rinik",
  "zk" => "Zack Kim",
}

## End of configuration
#######################################################################

unless File.exists?(".git")
  puts "This doesn't look like a git repository."
  exit 1
end

authors = ARGV.map do |initials|
  if AUTHORS[initials.downcase]
    AUTHORS[initials.downcase]
  else
    puts "Couldn't find author name for initials: #{initials}"
    exit 1
  end
end

if authors.any?
  if authors.size == 1
    authors = authors.first
  elsif authors.size == 2
    authors = authors.join(" and ")
  else
    authors = authors[0..-2].join(", ") + " and " + authors.last
  end

  initials = ARGV.join('/')

  `git config user.name '#{authors}'`
  `git config user.initials '#{initials}'`
  `git config user.email '#{PAIR_EMAIL}'`

  puts "user.name = #{authors}"
  puts "user.initials = #{initials}"
  puts "user.email = #{PAIR_EMAIL}"
else
  `git config --unset user.name`
  `git config --unset user.initials`
  `git config --unset user.email`

  puts "Unset user.name, user.initials, and user.email"
end
