#! /usr/bin/env bash

MOUNTPOINT=${HOME}/src
VOLNAME=sourcecode
ENCVOL=$HOME/sourcecode.tc

if [ ! -d ${MOUNTPOINT} ] ; then
    mkdir ${MOUNTPOINT}
fi

sudo losetup /dev/loop0 ${ENCVOL}
sudo cryptsetup luksOpen /dev/loop0 ${VOLNAME}
sudo mount /dev/mapper/${VOLNAME} ${MOUNTPOINT}
sudo chown -R pair:pair ${MOUNTPOINT}
