#! /usr/bin/env bash

LODEV=`sudo losetup -f`

MOUNTPOINT=${HOME}/src
VOLNAME=sourcecode
ENCVOL=$HOME/sourcecode.tc

if [ ! -d ${MOUNTPOINT} ] ; then
    mkdir ${MOUNTPOINT}
fi

sudo losetup ${LODEV} ${ENCVOL}
sudo cryptsetup luksOpen ${LODEV} ${VOLNAME}
sudo mount /dev/mapper/${VOLNAME} ${MOUNTPOINT}
sudo chown -R pair:pair ${MOUNTPOINT}
